version: 2.1

jobs:
  build_and_push_on_dev:
    docker:
      - image: kopilb/aws-docker:v0.1.0    
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Image and Push into ECR
          command: |
            aws configure set aws_access_key_id $DEV_AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $DEV_AWS_SECRET_ACCESS_KEY
            echo "$ENV_dev" | base64 -d >> /root/project/.env
            aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 277304117720.dkr.ecr.ap-south-1.amazonaws.com 
            docker compose -f docker-compose.${CIRCLE_BRANCH}.yml build
            docker compose -f docker-compose.${CIRCLE_BRANCH}.yml push

  deploy_to_ec2_on_dev:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: SSH into EC2, Pull Docker Image and Run
          command: |
            scp ./docker-compose.${CIRCLE_BRANCH}.yml $SSH_DEV_USER@$SSH_DEV_HOST:/home/ubuntu/projects/superskillup/backend/docker-compose.${CIRCLE_BRANCH}.yml
            echo "$ENV_dev" | base64 -d >> ./.env
            scp ./.env $SSH_DEV_USER@$SSH_DEV_HOST:/home/ubuntu/projects/superskillup/backend/.env
            ssh $SSH_DEV_USER@$SSH_DEV_HOST "aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 277304117720.dkr.ecr.ap-south-1.amazonaws.com
            cd /home/ubuntu/projects/superskillup/backend
            docker compose -f ./docker-compose.${CIRCLE_BRANCH}.yml pull
            docker compose -f ./docker-compose.${CIRCLE_BRANCH}.yml up --no-build --force-recreate -d"

workflows:
  build-and-deploy:
    jobs:
      - build_and_push_on_dev:
          context: ramailo-aws-context
          filters:
            branches:
              only:
                - main
      - deploy_to_ec2_on_dev:
          context: ramailo-aws-context
          requires:
            - build_and_push_on_dev
          filters:
            branches:
              only:
                - main