# Generated by Django 4.2.6 on 2024-03-18 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='question',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='subtopic',
            name='document',
        ),
        migrations.RemoveField(
            model_name='subtopic',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='document',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='slug',
        ),
        migrations.AddField(
            model_name='course',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
