# Generated by Django 5.0.3 on 2024-04-23 10:54

import app.utils.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_uservideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVideoWatched',
            fields=[
                ('id', models.CharField(db_index=True, default=app.utils.utils.get_char_uuid, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('sub_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos_watched', to='app.subtopic')),
                ('user_course_enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos_watched', to='app.usercourseenrollment')),
            ],
            options={
                'unique_together': {('user_course_enrollment', 'sub_topic')},
            },
        ),
        migrations.DeleteModel(
            name='UserVideo',
        ),
    ]
