# Generated by Django 5.0.3 on 2024-04-25 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_uservideowatched_delete_uservideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtopic',
            name='video_length',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
