# Generated by Django 5.0.3 on 2024-05-03 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_subtopic_video_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(blank=True, choices=[('Web Development', 'Web Development'), ('Frontend Development', 'Frontend Development'), ('Backend Development', 'Backend Development'), ('Full Stack Development', 'Full Stack Development'), ('Web Design & User Experience', 'Web Design & User Experience'), ('Management', 'Management'), ('Marketing', 'Marketing'), ('Artificial Intelligence', 'Artificial Intelligence'), ('Machine Learning', 'Machine Learning'), ('Testing & Automation', 'Testing & Automation'), ('Others', 'Others')], max_length=255, null=True),
        ),
    ]
