# Generated by Django 5.0.3 on 2024-03-13 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='otp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='otp_sent_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
