# Generated by Django 5.0.3 on 2024-05-06 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_course_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='gptreview',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='managerfeedback',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='subtopic',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='userassignmentsubmission',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['created_at']},
        ),
    ]
