# Generated by Django 5.0.3 on 2024-05-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_assignment_options_alter_course_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourseenrollment',
            name='interval_days',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='usercourseenrollment',
            name='next_topic_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usercourseenrollment',
            name='next_topic_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
